[package]
name = "taurpc"
authors = ["MatsDK"]
version = "0.5.0"
edition = "2021"
description = "A type-safe IPC layer for tauri commands"
documentation = "https://docs.rs/taurpc"
homepage = "https://github.com/MatsDK/TauRPC"
repository = "https://github.com/MatsDK/TauRPC"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = []
rust = "1.71"

[package.metadata."docs.rs"]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
taurpc-macros = { path = "./taurpc-macros", version = "=0.5.0" }

itertools = "0.13.0"
tauri = { version = "2.2.5", features = ["specta"] } 
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }

specta = { version = "=2.0.0-rc.22", features=["export", "function"] }
specta-serde = { version = "0.0.9", features = [] }
specta-typescript = { version = "0.0.9", features = ["function"] }
specta-macros = { version = "2.0.0-rc.17" }
heck = "0.5.0"
anyhow = "1.0.95"

[workspace]
members = [
  "taurpc-macros",
]
